title: NothingSpecial
author: YYJ
email: 906118808@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Personal Blog of YYJ

baseurl: ""
permalink: /:year/:month/:day/:title/
lang: zh-Hans # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting

github_username: yjyannnnn
# twitter_username:
instagram_username: yjyannnnn
# telegram_username: bambooom
disqus_shortname: troub1emaker
# Build settings
markdown: kramdown
# theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock